== What does this application do?

This application accepts requests from the client to create user profiles for Doctors who onboard to our medical services platform, consumers who are willing to avail the medical servcies online, interact with the medical practiioners to get basic medical diagnosis before heading to the hospital. This also includes a medical diagnosis delivery service using which doctor can PPE kits, other equipment which can be leveraged by people without having to head to the laboratories.


== Technical Details
- REST framework: link:https://spring.io/[Spring Boot]
- Database: PostgreSQL
- Version control: git
- Build automation: maven
- Containerization tools: Docker


== Developer Guide to run the code locally
==== `git clone https://github.com/himajasricherukuri/anytime-healthcare.git`

==== `cd /anytime-healthcare`

==== `git checkout main`

==== Local Postgres DB

* Spin up local PostgreSQL to serve as database

[source,bash]
----
./scripts/localPostgres.sh
----

==== `mvn clean install`

==== `java -jar -Dspring.profiles.active=local target/anytime-healthcare-0.0.1.jar`

== Accessing the application* Entry point to the application
http://localhost:8080/index.html#

* Swagger documentation for more details
http://localhost:8080/swagger-ui.html#/